# Generated by Django 2.2.7 on 2019-11-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen_info',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='kitchen_info',
            name='image',
        ),
    ]
