# Generated by Django 2.2.7 on 2019-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20191126_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulting',
            name='datetime',
            field=models.CharField(max_length=30),
        ),
    ]
