# Generated by Django 2.2.7 on 2019-11-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_auto_20191126_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulting',
            name='user',
        ),
        migrations.AlterField(
            model_name='consulting',
            name='datetime',
            field=models.TextField(),
        ),
    ]
