# Generated by Django 2.2.7 on 2019-12-09 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatbot', '0006_auto_20191127_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulting',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
