# Generated by Django 2.2.7 on 2019-12-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_auto_20191209_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kitchen_info',
        ),
    ]
