# Generated by Django 2.2.7 on 2019-12-27 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitchen_name', models.CharField(max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('image', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='move_pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movepop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('store_code', models.CharField(max_length=20)),
                ('mon_sales', models.IntegerField()),
                ('mon_sales_count', models.IntegerField()),
                ('weekdays_sales_rate', models.IntegerField()),
                ('weekend_sales_rate', models.IntegerField()),
                ('weekdays_sales_coount', models.IntegerField()),
                ('weekend_sales_count', models.IntegerField()),
                ('breakfast_sales', models.IntegerField()),
                ('lunch_sales', models.IntegerField()),
                ('dinner_sales', models.IntegerField()),
                ('men_sales_rate', models.IntegerField()),
                ('women_sales_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Start_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signgucd', models.IntegerField()),
                ('signgunm', models.CharField(max_length=20)),
                ('danger', models.CharField(max_length=20)),
                ('close', models.FloatField()),
                ('remain_term', models.FloatField()),
                ('plma', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='stay_pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('last_date', models.DateField()),
                ('time', models.IntegerField()),
                ('kitchen_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Kitchen_info')),
            ],
        ),
    ]
