# Generated by Django 2.2.6 on 2019-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='move_pop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdnm', models.CharField(max_length=20)),
                ('all_total', models.IntegerField()),
                ('men_total', models.IntegerField()),
                ('women_total', models.IntegerField()),
                ('total_20s', models.IntegerField()),
                ('total_30s', models.IntegerField()),
                ('total_40s', models.IntegerField()),
                ('total_50s', models.IntegerField()),
                ('total_60s', models.IntegerField()),
                ('men_20s', models.IntegerField()),
                ('men_30s', models.IntegerField()),
                ('men_40s', models.IntegerField()),
                ('men_50s', models.IntegerField()),
                ('men_60s', models.IntegerField()),
                ('women_20s', models.IntegerField()),
                ('women_30s', models.IntegerField()),
                ('women_40s', models.IntegerField()),
                ('women_50s', models.IntegerField()),
                ('women_60s', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Start_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signgucd', models.IntegerField()),
                ('signgunm', models.CharField(max_length=20)),
                ('danger', models.CharField(max_length=20)),
                ('close', models.FloatField()),
                ('remain_term', models.FloatField()),
                ('plma', models.FloatField()),
            ],
        ),
    ]
