# Generated by Django 2.2.6 on 2019-11-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_stay_pop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move_pop',
            name='rdnm',
            field=models.CharField(max_length=50),
        ),
    ]
