# Generated by Django 2.2.7 on 2019-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20191126_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move_pop',
            name='rdnm',
            field=models.CharField(max_length=20),
        ),
    ]
