# Generated by Django 2.2.7 on 2019-11-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation_time',
            old_name='kitchen_name',
            new_name='kitchen',
        ),
    ]
