# Generated by Django 2.2.7 on 2019-12-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Kitchen_info'),
        ),
        migrations.DeleteModel(
            name='Kitchen_info',
        ),
    ]
