# Generated by Django 2.2.7 on 2019-11-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191125_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation_time',
            new_name='Reservation',
        ),
    ]
