# Generated by Django 2.2.7 on 2019-12-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20191126_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_info',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
