# Generated by Django 2.2.7 on 2019-11-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20191126_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen_info',
            name='created_at',
        ),
    ]
