# Generated by Django 2.2.7 on 2019-12-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20191209_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen_info',
            name='created_at',
        ),
    ]
