# Generated by Django 2.2.7 on 2019-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_remove_kitchen_info_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen_info',
            name='capacity',
            field=models.IntegerField(default=6),
        ),
    ]
